# Imagen base
FROM python:3.12.9-slim-bookworm

# Establece directorio de trabajo
WORKDIR /app

# Instala Poetry
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir poetry

# Copia todo el proyecto al contenedor
COPY . /app/

# Configura e instala dependencias sin crear un entorno virtual
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

# Comando para ejecutar el cliente
CMD ["python", "cliente.py"]
